"""
analyze_oa_verification.py

Compare R vs K transition curves between simulation results and OA theory.
Supports three cases: all-to-all (K/N normalization), ER, and BA (no normalization).

Usage:
    python analyze_oa_verification.py --results_dir results_oa_verification

Input:
  - All-to-all: JSON file generated by kuramoto_alltoall.py in K_scan mode
  - ER/BA: CSV files generated by kuramoto_sim.py

Output:
  - Transition curve comparison plots (theory lines + simulation points)
    saved under analysis_plots/
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.cm as cm
from matplotlib.lines import Line2D
plt.rcParams.update({
    'font.size':       12,
    'axes.labelsize':  13,
    'axes.titlesize':  13,
    'legend.fontsize': 9,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
})
from scipy.stats import poisson
import os
import glob
import re
import json
import argparse


# =============================================
# OA Theory
# =============================================

def S_func(R):
    if R < 1e-12: return 1.0 / np.pi
    if R > 1 - 1e-12: return 0.0
    return (1 - R**2) * np.arctanh(R) / (np.pi * R)

def R_kick(R, eps):
    return R * np.cos(eps) + 2 * np.sin(eps) * S_func(R)


def oa_steady_state_homo(K, Delta, eps, tau, n_iter=3000, tol=1e-8):
    R = 0.01
    for _ in range(n_iter):
        R_old = R
        n_steps = 50
        dt = tau / n_steps
        for __ in range(n_steps):
            dR = -Delta * R + (K / 2) * R * (1 - R**2)
            R = max(0.0, min(1.0, R + dt * dR))
        R = max(0.0, min(1.0, R_kick(R, eps)))
        if abs(R - R_old) < tol:
            break
    return R


def get_degree_dist_coarse(network_type, kave, N=None):
    if network_type == 'ER':
        k_max = int(kave + 5 * np.sqrt(kave))
        k_all = np.arange(1, k_max + 1)
        Pk_all = poisson.pmf(k_all, kave)
        Pk_all /= Pk_all.sum()
        n_bins = min(15, len(k_all))
        edges = np.linspace(0.5, k_max + 0.5, n_bins + 1)
        k_rep, Pk_rep = [], []
        for i in range(n_bins):
            mask = (k_all >= edges[i]) & (k_all < edges[i + 1])
            if mask.sum() > 0 and Pk_all[mask].sum() > 1e-10:
                k_rep.append(np.average(k_all[mask], weights=Pk_all[mask]))
                Pk_rep.append(Pk_all[mask].sum())
        k_rep, Pk_rep = np.array(k_rep), np.array(Pk_rep)
        return k_rep, Pk_rep / Pk_rep.sum()

    elif network_type == 'BA':
        m = int(kave / 2)
        if N is not None:
            import networkx as nx
            all_degrees = []
            n_samples = min(20, max(5, N // 200))
            for s in range(n_samples):
                g = nx.barabasi_albert_graph(N, m, seed=s * 137)
                all_degrees.extend([d for _, d in g.degree()])
            all_degrees = np.array(all_degrees)
            k_min = m
            k_max = int(np.percentile(all_degrees, 99.5))
            k_all_clean = []
            Pk_all_clean = []
            for k in range(k_min, k_max + 1):
                cnt = np.sum(all_degrees == k)
                if cnt > 0:
                    k_all_clean.append(float(k))
                    Pk_all_clean.append(float(cnt))
            k_all = np.array(k_all_clean)
            Pk_all = np.array(Pk_all_clean)
            Pk_all /= Pk_all.sum()
        else:
            k_max = 300
            k_all = np.arange(m, k_max + 1).astype(float)
            Pk_all = 2.0 * m * (m + 1) / (k_all * (k_all + 1) * (k_all + 2))
            Pk_all /= Pk_all.sum()

        edges = np.unique(np.logspace(
            np.log10(k_all[0] - 0.5), np.log10(k_all[-1] + 0.5), 21
        ).astype(int))
        k_rep, Pk_rep = [], []
        for i in range(len(edges) - 1):
            mask = (k_all >= edges[i]) & (k_all < edges[i + 1])
            if mask.sum() > 0 and Pk_all[mask].sum() > 1e-10:
                k_rep.append(np.average(k_all[mask], weights=Pk_all[mask]))
                Pk_rep.append(Pk_all[mask].sum())
        k_rep, Pk_rep = np.array(k_rep), np.array(Pk_rep)
        return k_rep, Pk_rep / Pk_rep.sum()

    elif network_type == 'RR':
        d = int(kave)
        return np.array([float(d)]), np.array([1.0])

    else:
        raise ValueError(f"OA theory not applicable to {network_type}")


def oa_steady_state_hetero(k_arr, Pk, K, Delta, eps, tau, n_iter=3000, tol=1e-8):
    n = len(k_arr)
    k_mean = np.sum(k_arr * Pk)
    R_k = np.full(n, 0.03)
    for _ in range(n_iter):
        R_old = R_k.copy()
        n_steps = 50
        dt = tau / n_steps
        for __ in range(n_steps):
            H = np.sum(k_arr * Pk * R_k) / k_mean
            dR = -Delta * R_k + (k_arr * K / 2) * H * (1 - R_k**2)
            R_k = np.clip(R_k + dt * dR, 0, 1)
        for i in range(n):
            R_k[i] = max(0.0, min(1.0, R_kick(R_k[i], eps)))
        if np.max(np.abs(R_k - R_old)) < tol:
            break
    return np.sum(Pk * R_k)


def compute_theory_curve(network_type, K_values, Delta, eps, tau, kave=6.0, N=None):
    R_theory = []
    if network_type == 'alltoall':
        for K in K_values:
            R_theory.append(oa_steady_state_homo(K, Delta, eps, tau))
    else:
        k_arr, Pk = get_degree_dist_coarse(network_type, kave, N=N)
        for K in K_values:
            R_theory.append(oa_steady_state_hetero(k_arr, Pk, K, Delta, eps, tau))
    return np.array(R_theory)


# =============================================
# Simulation Data Loading
# =============================================

def load_alltoall_results(results_dir):
    json_files = glob.glob(os.path.join(results_dir, 'K_scan_*.json'))
    if not json_files:
        return None
    json_file = sorted(json_files)[-1]
    with open(json_file) as f:
        data = json.load(f)
    print(f"  Loaded all-to-all data: {json_file}")
    return data


def parse_network_filename(filename):
    basename = os.path.basename(filename)
    params = {}
    for net in ['ER', 'BA', 'WS', 'RR']:
        if f'_{net}_' in basename:
            params['network'] = net
            break
    patterns = {
        'N': r'_N(\d+)',
        'kave': r'_kave([\d.]+)',
        'K': r'_K([\d.]+)',
        'eps': r'_eps(-?[\d.]+)',
        'interval': r'_interval([\d.]+)',
    }
    for key, pattern in patterns.items():
        match = re.search(pattern, basename)
        if match:
            params[key] = float(match.group(1))
    params['random'] = '_random' in basename
    return params


def extract_steady_state_R(filepath, t_fraction=0.5):
    try:
        df = pd.read_csv(filepath)
    except Exception as e:
        print(f"  Warning: Could not read {filepath}: {e}")
        return None, None
    if 'R_mean' not in df.columns:
        return None, None
    tmax = df['time'].max()
    mask = df['time'] > tmax * t_fraction
    R_mean = df.loc[mask, 'R_mean'].mean()
    R_columns = [col for col in df.columns if col.startswith('R_run')]
    if R_columns:
        R_ss_per_run = df.loc[mask, R_columns].mean(axis=0)
        R_std = R_ss_per_run.std()
    else:
        R_std = 0.0
    return R_mean, R_std


def load_network_results(results_dir):
    csv_files = glob.glob(os.path.join(results_dir, 'results_*_all_runs.csv'))
    records = []
    for filepath in sorted(csv_files):
        params = parse_network_filename(filepath)
        if 'network' not in params:
            continue
        R_mean, R_std = extract_steady_state_R(filepath)
        if R_mean is not None:
            params['R_mean'] = R_mean
            params['R_std'] = R_std
            records.append(params)
    if not records:
        return pd.DataFrame()
    return pd.DataFrame(records)


# =============================================
# Legend helpers
# =============================================

def make_legends(ax, eps_pos, red_colors, blue_colors, loc1='upper left', loc2='upper right'):z
    # (1) epsilon color legend: +large to 0 to -large
    color_handles = []
    for i, ev in enumerate(reversed(eps_pos)):
        ri = len(eps_pos) - 1 - i
        color_handles.append(
            Line2D([0], [0], color=red_colors[ri], lw=2.5,
                   label=fr'$\epsilon=+{ev}$'))
    color_handles.append(
        Line2D([0], [0], color='k', lw=2.5, label=r'$\epsilon=0$'))
    for i, ev in enumerate(eps_pos):
        color_handles.append(
            Line2D([0], [0], color=blue_colors[i], lw=2.5,
                   label=fr'$\epsilon=-{ev}$'))

    # (2) theory vs simulation legend
    symbol_handles = [
        Line2D([0], [0], color='gray', lw=2.5, label='OA theory'),
        Line2D([0], [0], color='gray', lw=0, marker='o',
               markerfacecolor='none', markeredgewidth=1.5,
               ms=7, label='Simulation'),
    ]

    leg1 = ax.legend(handles=color_handles, loc=loc1,
                     framealpha=0.9, ncol=1)
    ax.add_artist(leg1)
    ax.legend(handles=symbol_handles, loc=loc2, framealpha=0.9)


# =============================================
# Plotting
# =============================================

def plot_alltoall_transition(alltoall_data, Delta, tau, output_dir):
    if alltoall_data is None:
        print("  No all-to-all data found, skipping.")
        return

    K_c = 2 * Delta
    K_ratios = np.array(alltoall_data['K_ratio'])
    eps_values = alltoall_data.get('eps_values', [0.0, 0.05, -0.05])
    eps_pos = sorted(set(abs(e) for e in eps_values if e > 0))
    n_pos = len(eps_pos)
    red_colors  = [cm.Reds(0.4  + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]
    blue_colors = [cm.Blues(0.4 + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]

    fig, ax = plt.subplots(figsize=(5.5, 5))

    K_th = np.linspace(K_ratios.min() * K_c, K_ratios.max() * K_c, 80)
    K_th_ratio = K_th / K_c

    # Theory curves
    R_th_0 = compute_theory_curve('alltoall', K_th, Delta, 0.0, tau)
    ax.plot(K_th_ratio, R_th_0, 'k-', lw=2.5)
    for i, eps_v in enumerate(eps_pos):
        ax.plot(K_th_ratio,
                compute_theory_curve('alltoall', K_th, Delta,  eps_v, tau),
                '-', color=red_colors[i], lw=2.5)
        ax.plot(K_th_ratio,
                compute_theory_curve('alltoall', K_th, Delta, -eps_v, tau),
                '-', color=blue_colors[i], lw=2.5)

    # Simulation points
    key0 = 'R_eps+0.000'
    if key0 in alltoall_data:
        ax.plot(K_ratios, alltoall_data[key0], 'o', color='k', ms=7,
                markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
    elif 'R_none' in alltoall_data:
        ax.plot(K_ratios, alltoall_data['R_none'], 'o', color='k', ms=7,
                markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
    for i, eps_v in enumerate(eps_pos):
        key_p = f'R_eps+{eps_v:.3f}'
        key_n = f'R_eps-{eps_v:.3f}'
        if key_p in alltoall_data:
            ax.plot(K_ratios, alltoall_data[key_p], 'o', color=red_colors[i],
                    ms=7, markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
        if key_n in alltoall_data:
            ax.plot(K_ratios, alltoall_data[key_n], 'o', color=blue_colors[i],
                    ms=7, markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)

    ax.axvline(1.0, color='gray', ls=':', lw=1.2, alpha=0.5)
    ax.set_xlabel(r'$K / K_c$')
    ax.set_ylabel('$R$')
    ax.set_ylim(-0.02, 1.02)
    make_legends(ax, eps_pos, red_colors, blue_colors)

    plt.tight_layout()
    fname = os.path.join(output_dir, 'transition_alltoall.png')
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.pdf'), bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.eps'), bbox_inches='tight')
    plt.close()
    print(f"  Saved {fname}")


def plot_network_transition_simple(df, network_type, Delta, tau, kave, output_dir, panel_label=None):
    subset = df[df['network'] == network_type].copy()
    if len(subset) == 0:
        print(f"  No data for {network_type}, skipping.")
        return

    if 'eps' not in subset.columns:
        subset['eps'] = 0.0
    subset['eps'] = subset['eps'].fillna(0.0)

    all_eps = sorted(subset['eps'].unique())
    eps_pos = sorted(set(abs(e) for e in all_eps if e > 0.001))
    n_pos = len(eps_pos)
    red_colors  = [cm.Reds(0.4  + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]
    blue_colors = [cm.Blues(0.4 + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]

    try:
        k_arr, Pk = get_degree_dist_coarse(network_type, kave)
        k_mean = np.sum(k_arr * Pk)
        k2 = np.sum(k_arr**2 * Pk)
        K_c = 2 * Delta * k_mean / k2
        has_theory = True
    except ValueError:
        K_c = None
        has_theory = False

    fig, ax = plt.subplots(figsize=(5.5, 5))

    if has_theory:
        K_min = max(subset['K'].min() * 0.5, 0.001)
        K_max = subset['K'].max() * 1.1
        K_th = np.linspace(K_min, K_max, 80)

        ax.plot(K_th,
                compute_theory_curve(network_type, K_th, Delta, 0.0, tau, kave),
                'k-', lw=2.5)
        for i, eps_v in enumerate(eps_pos):
            ax.plot(K_th,
                    compute_theory_curve(network_type, K_th, Delta,  eps_v, tau, kave),
                    '-', color=red_colors[i], lw=2.5)
            ax.plot(K_th,
                    compute_theory_curve(network_type, K_th, Delta, -eps_v, tau, kave),
                    '-', color=blue_colors[i], lw=2.5)
        ax.axvline(K_c, color='gray', ls=':', lw=1.2, alpha=0.5)

    # Simulation points
    def _pts(eps_val):
        s = subset[np.isclose(subset['eps'], eps_val, atol=0.001)]
        if 'random' in s.columns:
            s = s[~s['random']]
        return s.sort_values('K')

    s0 = _pts(0.0)
    if len(s0):
        ax.plot(s0['K'], s0['R_mean'], 'o', color='k', ms=7, alpha=0.8,
                markerfacecolor='none', markeredgewidth=1.5)
    for i, eps_v in enumerate(eps_pos):
        sp = _pts( eps_v); sn = _pts(-eps_v)
        if len(sp):
            ax.plot(sp['K'], sp['R_mean'], 'o', color=red_colors[i], ms=7,
                    alpha=0.8, markerfacecolor='none', markeredgewidth=1.5)
        if len(sn):
            ax.plot(sn['K'], sn['R_mean'], 'o', color=blue_colors[i], ms=7,
                    alpha=0.8, markerfacecolor='none', markeredgewidth=1.5)

    ax.set_xlabel('$K$')
    ax.set_ylabel('$R$')
    ax.set_ylim(-0.02, 1.02)
    make_legends(ax, eps_pos, red_colors, blue_colors)

    if panel_label is not None:
        ax.set_title(f'({panel_label}) {network_type}')

    plt.tight_layout()
    fname = os.path.join(output_dir, f'transition_{network_type}.png')
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.pdf'), bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.eps'), bbox_inches='tight')
    plt.close()
    print(f"  Saved {fname}")


def plot_combined_summary(alltoall_data, df_net, Delta, tau, kave, output_dir,
                          normalize_K=False, N_net=None):
    if alltoall_data is not None and 'eps_values' in alltoall_data:
        eps_all = alltoall_data['eps_values']
    elif len(df_net) > 0 and 'eps' in df_net.columns:
        eps_all = sorted(df_net['eps'].dropna().unique())
    else:
        eps_all = [0.0, 0.03, -0.03, 0.05, -0.05, 0.07, -0.07]

    eps_pos = sorted(set(abs(e) for e in eps_all if e > 0.001))
    n_pos = len(eps_pos)
    red_colors  = [cm.Reds(0.4  + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]
    blue_colors = [cm.Blues(0.4 + 0.5 * i / max(n_pos - 1, 1)) for i in range(n_pos)]

    def _plot_panel(ax, net_type, K_c_oa, x_is_ratio=False):
        if x_is_ratio:
            K_range_ratio = np.linspace(0.3, 3.0, 80)
            K_th = K_range_ratio * K_c_oa
            x_theory = K_range_ratio
        else:
            if len(df_net) > 0 and net_type in df_net['network'].values:
                sub = df_net[df_net['network'] == net_type]
                K_range_abs = np.linspace(
                    max(sub['K'].min() * 0.5, 0.001),
                    sub['K'].max() * 1.1, 80)
            else:
                K_range_abs = np.linspace(0.01, 0.4, 80)
            K_th = K_range_abs
            x_theory = K_range_abs

        N_for_theory = N_net if net_type == 'BA' else None

        # Theory curves
        ax.plot(x_theory,
                compute_theory_curve('alltoall' if net_type == 'alltoall' else net_type,
                                     K_th, Delta, 0.0, tau, kave, N=N_for_theory),
                'k-', lw=2.5)
        for i, eps_v in enumerate(eps_pos):
            ax.plot(x_theory,
                    compute_theory_curve('alltoall' if net_type == 'alltoall' else net_type,
                                         K_th, Delta,  eps_v, tau, kave, N=N_for_theory),
                    '-', color=red_colors[i], lw=2.5)
            ax.plot(x_theory,
                    compute_theory_curve('alltoall' if net_type == 'alltoall' else net_type,
                                         K_th, Delta, -eps_v, tau, kave, N=N_for_theory),
                    '-', color=blue_colors[i], lw=2.5)

        # Simulation points
        if net_type == 'alltoall' and alltoall_data is not None:
            K_ratios = np.array(alltoall_data['K_ratio'])
            x_sim = K_ratios
            key0 = 'R_eps+0.000'
            if key0 in alltoall_data:
                ax.plot(x_sim, alltoall_data[key0], 'o', color='k', ms=7,
                        markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
            elif 'R_none' in alltoall_data:
                ax.plot(x_sim, alltoall_data['R_none'], 'o', color='k', ms=7,
                        markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
            for i, eps_v in enumerate(eps_pos):
                key_p = f'R_eps+{eps_v:.3f}'
                key_n = f'R_eps-{eps_v:.3f}'
                if key_p in alltoall_data:
                    ax.plot(x_sim, alltoall_data[key_p], 'o', color=red_colors[i],
                            ms=7, markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)
                if key_n in alltoall_data:
                    ax.plot(x_sim, alltoall_data[key_n], 'o', color=blue_colors[i],
                            ms=7, markerfacecolor='none', markeredgewidth=1.5, alpha=0.8)

        elif len(df_net) > 0 and net_type in df_net['network'].values:
            sub_all = df_net[df_net['network'] == net_type].copy()
            sub_all['eps'] = sub_all['eps'].fillna(0.0)

            def _x_pts(K_vals):
                return K_vals / K_c_oa if x_is_ratio else K_vals

            def _pts(eps_val):
                s = sub_all[np.isclose(sub_all['eps'], eps_val, atol=0.001)]
                if 'random' in s.columns: s = s[~s['random']]
                return s.sort_values('K')

            s0 = _pts(0.0)
            if len(s0):
                ax.plot(_x_pts(s0['K'].values), s0['R_mean'], 'o', color='k',
                        ms=7, alpha=0.8, markerfacecolor='none', markeredgewidth=1.5)
            for i, eps_v in enumerate(eps_pos):
                sp = _pts( eps_v); sn = _pts(-eps_v)
                if len(sp):
                    ax.plot(_x_pts(sp['K'].values), sp['R_mean'], 'o',
                            color=red_colors[i], ms=7, alpha=0.8,
                            markerfacecolor='none', markeredgewidth=1.5)
                if len(sn):
                    ax.plot(_x_pts(sn['K'].values), sn['R_mean'], 'o',
                            color=blue_colors[i], ms=7, alpha=0.8,
                            markerfacecolor='none', markeredgewidth=1.5)

        ax.axvline(1.0 if x_is_ratio else K_c_oa, color='gray', ls=':', lw=1.2, alpha=0.5)
        ax.set_ylim(-0.02, 1.02)

    # Determine panels
    panels = []
    if alltoall_data is not None:
        panels.append(('alltoall', 2 * Delta, True, 'All-to-all'))

    has_er = len(df_net) > 0 and 'ER' in df_net['network'].values
    has_ba = len(df_net) > 0 and 'BA' in df_net['network'].values

    if has_er:
        try:
            k_arr_er, Pk_er = get_degree_dist_coarse('ER', kave)
            K_c_er = 2 * Delta * np.sum(k_arr_er * Pk_er) / np.sum(k_arr_er**2 * Pk_er)
        except:
            K_c_er = 0.143
        panels.append(('ER', K_c_er, normalize_K, 'ER'))

    if has_ba:
        try:
            k_arr_ba, Pk_ba = get_degree_dist_coarse('BA', kave, N=N_net)
            K_c_ba = 2 * Delta * np.sum(k_arr_ba * Pk_ba) / np.sum(k_arr_ba**2 * Pk_ba)
        except:
            K_c_ba = 0.071
        panels.append(('BA', K_c_ba, normalize_K, 'BA'))

    if len(panels) == 0:
        print("  No data to plot.")
        return

    n_panels = len(panels)
    fig, axes = plt.subplots(n_panels, 1, figsize=(5.5, 5.0 * n_panels))
    if n_panels == 1:
        axes = [axes]

    labels = 'abcdefgh'
    for idx, (net_type, K_c_oa, x_ratio, title_net) in enumerate(panels):
        ax = axes[idx]
        _plot_panel(ax, net_type, K_c_oa, x_is_ratio=x_ratio)
        ax.set_xlabel(r'$K / K_c$' if x_ratio else '$K$')
        ax.set_ylabel('$R$')
        make_legends(ax, eps_pos, red_colors, blue_colors,
                     loc1='upper left', loc2='upper right')

    plt.tight_layout()
    suffix = '_normalized' if normalize_K else ''
    fname = os.path.join(output_dir, f'transition_combined{suffix}.png')
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.pdf'), bbox_inches='tight')
    plt.savefig(fname.replace('.png', '.eps'), bbox_inches='tight')
    plt.close()
    print(f"  Saved {fname}")


# =============================================
# Main
# =============================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--results_dir',  default='results_oa_verification')
    parser.add_argument('--output_dir',   default='analysis_plots')
    parser.add_argument('--Delta',  type=float, default=0.5)
    parser.add_argument('--tau',    type=float, default=0.3)
    parser.add_argument('--kave',   type=float, default=6.0)
    parser.add_argument('--N_net',  type=int,   default=1000)
    parser.add_argument('--alltoall_dir', default=None)
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    print(f"Delta={args.Delta}, tau={args.tau}, kave={args.kave}")

    aa_dir = args.alltoall_dir or args.results_dir
    alltoall_data = load_alltoall_results(aa_dir)
    df_net = load_network_results(args.results_dir)

    if alltoall_data is None and len(df_net) == 0:
        print("No data found.")
        exit(1)

    print("\n--- Individual plots ---")
    if alltoall_data is not None:
        plot_alltoall_transition(alltoall_data, args.Delta, args.tau, args.output_dir)
    if len(df_net) > 0:
        for net, label in [('ER', 'a'), ('BA', 'b')]:
            plot_network_transition_simple(
                df_net, net, args.Delta, args.tau, args.kave, args.output_dir,
                panel_label=label)

    print("\n--- Combined plot ---")
    plot_combined_summary(alltoall_data, df_net, args.Delta, args.tau,
                          args.kave, args.output_dir,
                          normalize_K=False, N_net=args.N_net)
    plot_combined_summary(alltoall_data, df_net, args.Delta, args.tau,
                          args.kave, args.output_dir,
                          normalize_K=True, N_net=args.N_net)

    print(f"\nAll plots saved to {args.output_dir}/")